name: Multi-Image Sync to Private Registry via Skopeo

on:
  # schedule:
    # - cron: '0 4,10,16,22 * * *'  # UTC 16:00 对应北京时间 00:00
  workflow_dispatch:

jobs:
  sync-images:
    runs-on: ubuntu-latest
    

    steps:
      # ---------------------
      # 阶段1：环境初始化
      # ---------------------
      - name: Setup Skopeo
        run: |
          sudo apt install -y jq  # 安装核心工具

      # ---------------------
      # 阶段2：镜像元数据获取
      # ---------------------
      - name: Fetch image digest
        id: get-digest
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          API_URL="https://hub.docker.com/v2/repositories/emby/embyserver/tags/4.9.0.43"
          # digest=$(curl -sLH "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" $API_URL | jq -r '.digest')
          # digest_images=$(curl -sLH "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" $API_URL | jq -r '.images[].digest')
          # last_pushed=$(curl -sLH "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" $API_URL | jq -r '.tag_last_pushed')
          # last_pushed_images=$(curl -sLH "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" $API_URL | jq -r '.images[].last_pushed')
          # last_pushed_date=$(echo "$(curl -sLH "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" $API_URL | jq -r '.tag_last_pushed')" | cut -d'T' -f1 | tr -d '-')
          echo "digest=$digest" >> $GITHUB_OUTPUT
          echo "$(curl -sLH "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" $API_URL | jq -r '.digest')"
          # echo "$digest_images"
          echo "$(echo "$(curl -sLH "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" $API_URL | jq -r '.tag_last_pushed')" | cut -d'T' -f1 | tr -d '-')"
          # echo "$last_pushed_images"
