name: Sync Release
on:
  workflow_dispatch: # 允许手动触发
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Release
        uses: aminya/sync-releases@v1
        with:
          source: "源仓库所有者/源仓库名" # 例如: "lodash/lodash"
          destination: "你的用户名/你的仓库名"
          token: ${{ secrets.GITHUB_TOKEN }} # 使用默认Token即可
